### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by shdudwns** [SpigotPE-Team/SpigotPE#20]
Please let me live again ...Developers.
And what about the bluelight or rocker folk version?
Two rolls of folk pork version 2 are in my repo
@Asuna-Yuuki

**Comment by Asuna-Yuuki** [comment]
Uhh no it isn't dead @shdudwns I invite you if you want we all have vacation so yea

**Comment by shdudwns** [comment]
@Asuna-Yuuki Do you want to develop tesseract?

**Comment by Asuna-Yuuki** [comment]
@shdudwns yea but Apple developer don't let me and I understand it

**Comment by shdudwns** [comment]
@Asuna-Yuuki I am Mark Server administrator.
I want to use a lot of tesseract too.
But when tesseract was ruined ...
But can you tell me why tesseract doesn't work?

**Comment by shdudwns** [comment]
Did you know that the tesseract has been rebuilt and disappeared today?

**Comment by shdudwns** [comment]
@Asuna-Yuuki Can I add a tesseract once?

**Comment by Asuna-Yuuki** [comment]
@shdudwns yes

**Comment by shdudwns** [comment]
Because I'm a beginner, what's the recipe for folders?
And I'm a novice, can you help me?
@Asuna-Yuuki

**Comment by Asuna-Yuuki** [comment]
Yes I help

**Comment by Asuna-Yuuki** [comment]
But if Apple developer says that we take it down it will be taken down

**Comment by Fabiansigala** [comment]
Hi

**Comment by shdudwns** [comment]
@Fabiansigala Hi
https://github.com/ServerSoftwareArchiveTeam

**Comment by Fabiansigala** [comment]
@shdudwns can you make me owner?

**Comment by Fabiansigala** [comment]
I remember RockySoftware before NFGamer took over and went crazy

**Comment by shdudwns** [comment]
@Fabiansigala You come here and develop together.

**Comment by shdudwns** [comment]
https://github.com/ServerSoftwareArchiveTeam

**Comment by NFGamerMC** [comment]
@Fabiansigala I did not go crazy i got tired with copy pastas

**Comment by Fabiansigala** [comment]
@NFGamerMC oh... Ok...
