### ISSUE TITLE
4 bugs

### ISSUE THREAD

**Issue by amirabas** [SpigotPE-Team/SpigotPE#23]
Hello
I've encountered bugs that I'm telling you to fix
1-purechat runs but does not work in the game
2. We do not have a join message
3-commands do not work like / tp(I do not know how to edit command.json)
4. If you may support the EssentialsPE plugin

**Comment by Asuna-Yuuki** [comment]
@amirabas  first one i know about commands they work on mcpe 1.2 only they don't show up obout essentials I patch them up

**Comment by ExplodingCraftPE** [comment]
we will try to fix it

**Comment by Asuna-Yuuki** [comment]
fixt  c7f8780
