### ISSUE TITLE
Gamemode Command Not Working In Game

### ISSUE THREAD

**Issue by alexbgameson** [SpigotPE-Team/SpigotPE#25]
The command /gamemode is not working when you go to change you gamemode in game.

**Comment by MrLukePotatoes** [comment]
Sorry for that! Me and the staff will maybe have a meeting. And I will just
tell them to fix it with me.

-Luke (Co-Owner of SpigotPE)

**Comment by Asuna-Yuuki** [comment]
Use the latest version
