### ISSUE TITLE
TP error

### ISSUE THREAD

**Issue by shdudwns** [SpigotPE-Team/SpigotPE#3]
pocketmine\utils\BinaryStream::putLFloat() must be of the type float, string given, called in /root/pm/src/pocketmine/network/mcpe/protocol/DataPacket.php on line 354
12:30:21 [CRITICAL] TypeError: "Argument 1 passed to pocketmine\utils\BinaryStream::putLFloat() must be of the type float, string given, called in /root/pm/src/pocketmine/network/mcpe/protocol/DataPacket.php on line 354" (EXCEPTION) in "/src/pocketmine/utils/BinaryStream" at line 188
12:30:21 [DEBUG] #0 /src/pocketmine/network/mcpe/protocol/DataPacket(354): pocketmine\utils\BinaryStream->putLFloat(string 128.6893)
12:30:21 [DEBUG] #1 /src/pocketmine/network/mcpe/protocol/MovePlayerPacket(70): pocketmine\network\mcpe\protocol\DataPacket->putVector3f(string 128.6893, double 6.62, string 127.5172)
12:30:21 [DEBUG] #2 /src/pocketmine/network/mcpe/RakLibInterface(195): pocketmine\network\mcpe\protocol\MovePlayerPacket->encode()
12:30:21 [DEBUG] #3 /src/pocketmine/Player(1103): pocketmine\network\mcpe\RakLibInterface->putPacket(pocketmine\Player object, pocketmine\network\mcpe\protocol\MovePlayerPacket object, boolean , boolean )
12:30:21 [DEBUG] #4 /src/pocketmine/Player(4156): pocketmine\Player->dataPacket(pocketmine\network\mcpe\protocol\MovePlayerPacket object)
12:30:21 [DEBUG] #5 /src/pocketmine/Player(4210): pocketmine\Player->sendPosition(pocketmine\Player object, integer 264, integer 15, integer 1)
12:30:21 [DEBUG] #6 /src/pocketmine/Player(1808): pocketmine\Player->checkTeleportPosition()
12:30:21 [DEBUG] #7 /src/pocketmine/level/Level(790): pocketmine\Player->onUpdate(integer 2876)
12:30:21 [DEBUG] #8 /src/pocketmine/Server(2374): pocketmine\level\Level->doTick(integer 2876)

**Comment by BlawoHD** [comment]
I fix this soon

**Comment by shdudwns** [comment]
@BlawoHD okay

**Comment by caspervanneck** [comment]
shult be fixt else its a plugin issue
