### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by SirDoz** [SpigotPE-Team/SpigotPE#39]
Ive just wiped out my server to switch and upgrade to alpha-7 api 3.0.0. I chose SpigotPE because it has both Genesys and Teressract combined

Anytime I try to connect to my server it keeps giving me this error and the server would crash..

Fatal error: Declaration of pocketmine\tile\BeaconDelayedCheckTask::onRun($currentTick) must be compatible with pocketmine\scheduler\Task::onRun(int $currentTick) in phar:///jar/pocketmine/spigotpe/1.1.0-ALPHA7/SpigotPE.phar/src/pocketmine/tile/BeaconDelayedCheckTask.php on line 0

And something to do with Pufferfish.php

**Comment by Asuna-Yuuki** [comment]
@SirDoz we will fix it soon thnx for reporting

**Comment by MrLukePotatoes** [comment]
Hello SirDoz or Afox, We will fix this as soon as possible and also the
crash is about the "Beacon Block"

From
MrLukePotatoes
Co-Owner of SpigotPE

My Discord:
MrLukePotatoes#1488

**Comment by Asuna-Yuuki** [comment]
fixt i think
