### ISSUE TITLE
Fix this please

### ISSUE THREAD

**Issue by Baducai** [SpigotPE-Team/SpigotPE#40]
Notice: Undefined property: pocketmine\network\mcpe\protocol\LoginPacket::$deviceModel in /home/BedWars/src/pocketmine/Player.php on line 2402

Notice: Undefined property: pocketmine\network\mcpe\protocol\LoginPacket::$deviceOS in /home/BedWars/src/pocketmine/Player.php on line 2403

**Comment by MrLukePotatoes** [comment]
I think we do not support that plugin yet for SpigotPE, We will try to
support the plugin


-From
MrLukePotatoes
Co-Owner of SpigotPE

**Comment by Asuna-Yuuki** [comment]
fixt
