### ISSUE TITLE
Fix this

### ISSUE THREAD

**Issue by Baducai** [SpigotPE-Team/SpigotPE#42]
Warning: Declaration of pocketmine\block\Chest::place(pocketmine\item\Item $item, pocketmine\block\Block $blockReplace, pocketmine\block\Block $blockClicked, int $face, pocketmine\math\Vector3 $facePos, pocketmine\Player $player = NULL): bool should be compatible with pocketmine\block\Block::place(pocketmine\item\Item $item, pocketmine\block\Block $block, pocketmine\block\Block $target, $face, $fx, $fy, $fz, pocketmine\Player $player = NULL) in /home/BedWars/src/pocketmine/block/Chest.php on line 182

**Comment by Asuna-Yuuki** [comment]
thats a plugin problem
