### ISSUE TITLE
PHP 7.2 installer script?

### ISSUE THREAD

**Issue by ZizzyZizzy** [SpigotPE-Team/SpigotPE#46]
08.09 15:32:19 [Server] INFO [CRITICAL] You must use PHP >= 7.2
08.09 15:32:19 [Server] INFO [CRITICAL] Please use the installer provided on the homepage.

What installer on which home page? That message looks copied and pasted from PMMP source, and their PHP 7.2 installer doesn't work on CentOS 6.9.

checking size of off_t... 0
configure: error: off_t undefined; check your library configuration

I've tried everything I could find about that vague, less than helpful error.  libzip and libzip5 are both installed. libxml is installed. No idea what this could be complaining about.

**Comment by WiliRodin** [comment]
Its error droped for me too

**Comment by Fabiansigala** [comment]
weird
we will work on this
we posted the php binarys on our home page and github :-P

**Comment by Fabiansigala** [comment]
any other errors?

**Comment by Kirito-Kazuto** [comment]
Upgrade your php

**Comment by ZizzyZizzy** [comment]
@Kirito-Kazuto Seriously?

Me: "We are unable to compile the new version of PHP"
You: "Upgrade your PHP"

WTF?

**Comment by ZizzyZizzy** [comment]
@Fabiansigala Thanks. I see it now:
https://github.com/SpigotPE-Team/php-binarys

Although, it's spelled binaries. No offense, it's just me and my semi-OCD/perfectionist nature.

**Comment by ZizzyZizzy** [comment]
@Fabiansigala I've actually tried that binary before. It doesn't work on a fully updated CentOS 6.9 because it was compiled against a newer version of GLIBC:

```
./php: /lib64/libm.so.6: version `GLIBC_2.15' not found (required by ./php)
./php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./php)
./php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/src/test/bin/php7/bin/../lib/libz.so.1)
./php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/src/test/bin/php7/bin/../lib/libyaml-0.so.2)
./php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/src/test/bin/php7/bin/../lib/libcurl.so.4)
./php: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /usr/local/src/test/bin/php7/bin/../lib/libcurl.so.4)

```

This is very frustrating. CentOS 6.9 is NOT that old PHP 7.2 SHOULD compile just fine, I just can't figure out how to get past that vague error about off_t. I can't just magically upgrade 10 production servers from CentOS 6.9 to 7 because this stupid thing won't compile.

**Comment by Kirito-Kazuto** [comment]
Just take the pmmp bin

**Comment by Fabiansigala** [comment]
😝

**Comment by Fabiansigala** [comment]
Btw I added php 7.2 for windows on https://github.com/SpigotPE-Team/php-binarys

**Comment by WiliRodin** [comment]
Add for android support please.

**Comment by ZizzyZizzy** [comment]
@Kirito-Kazuto The PMMP binaries are compiled using the same GLIBC, which is newer than on CentOS 6.9.

We do plan on updating to CentOS 7, as 6.9 support for many things seems to be dragging very slowly. However, that of course takes time when you're talking about 10+ production, revenue-generating servers. It would sure be nice to understand what the **off_t undefined** error was actually referring to so I can attempt to update whatever library it's checking.

**Comment by Fabiansigala** [comment]
@ZizzyZizzy do you own a hosting company or what?

**Comment by Kirito-Kazuto** [comment]
@ZizzyZizzy you can use https://github.com/SpigotPE-Team/Rocky this uses the old php 7.0.x

**Comment by ZizzyZizzy** [comment]
@Fabiansigala Yes, and thank you. I'll use that branch!

**Comment by ZizzyZizzy** [comment]
@Fabiansigala There is only a single file in that repo and it's the README file.
