### ISSUE TITLE
php 7.2 error

### ISSUE THREAD

**Issue by MiguelPlayzMCPE** [SpigotPE-Team/SpigotPE#47]
Won't work I have php 7.2 and a 64 bit device help!

**Comment by WiliRodin** [comment]
Its caused by the build from circleci.
Idk how fix it too :'(

**Comment by Fabiansigala** [comment]
Do you think you can show us a screen recording? @wiliRodin @MiguelPlayzMCPE

**Comment by Kirito-Kazuto** [comment]
I don't think so if it's your config then delete it

**Comment by Fabiansigala** [comment]
I will check our back end in the code brb

**Comment by Fabiansigala** [comment]
Nothing wrong

**Comment by Kirito-Kazuto** [comment]
fixt

**Comment by Kirito-Kazuto** [comment]
@MiguelPlayzMCPE we use php 7.0 again plz read the readme
