### ISSUE TITLE
Can you change the location of network internal files?

### ISSUE THREAD

**Issue by shdudwns** [SpigotPE-Team/SpigotPE#5]
pocketmine\network\mcpe\protocol -> mine\network\protocol

**Comment by caspervanneck** [comment]
NO its pmmp fork not genisyspro

**Comment by shdudwns** [comment]
@caspervanneck 
But most of the flags are pocketmine \ network \ protocol

**Comment by caspervanneck** [comment]
yes  but i ant change it

**Comment by caspervanneck** [comment]
most cool plugin suport this

**Comment by shdudwns** [comment]
Do you know someone called solo5star?
@caspervanneck

**Comment by caspervanneck** [comment]
@shdudwns no idk him

**Comment by shdudwns** [comment]
But why is pocketmine \ network \ mcpe \ protocol?
Is not pocketmine \ network \ protocol useful?
@caspervanneck

**Comment by shdudwns** [comment]
Please reconsider.
Many plugins do not work with pocketmine \ network \ mcpe \ protocol
@caspervanneck

**Comment by caspervanneck** [comment]
yes i know but ask that at pmmp

**Comment by caspervanneck** [comment]
@shdudwns

**Comment by caspervanneck** [comment]
its not that i changed its pmmp

**Comment by shdudwns** [comment]
@caspervanneck yes......

**Comment by caspervanneck** [comment]
i whant to change it back  but its to much work to port it back like te old days @shdudwns

**Comment by caspervanneck** [comment]
if you want to make changes i invite you

**Comment by shdudwns** [comment]
No.I do not know how to develop.
What do you need to know to develop?
@caspervanneck

**Comment by caspervanneck** [comment]
@shdudwns not much a pc and a brain

**Comment by shdudwns** [comment]
@caspervanneck Don't you need to know the Php code?

**Comment by caspervanneck** [comment]
yes indeed

**Comment by shdudwns** [comment]
I am not familiar with the php code.
@caspervanneck
