### ISSUE TITLE
Fix EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by BlawoHD** [SpigotPE-Team/SpigotPE#9]
![img_4747](https://user-images.githubusercontent.com/22114921/27836634-8ec8515a-60e0-11e7-9cd1-e6ddae538176.PNG)

**Comment by caspervanneck** [comment]
try it shult be fixt at 093aeab  @BlawoHD

**Comment by caspervanneck** [comment]
7af0119231478435b9b9c381d53e6f693ae195a5
